// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  var Back, Bounce, Phaser, Quadratic, Rectangle, WHITE, YELLOW, dat, onDown, onUp, tweenGui;

  dat = this.dat, Phaser = this.Phaser;

  Back = Phaser.Easing.Back;

  Bounce = Phaser.Easing.Bounce;

  Quadratic = Phaser.Easing.Quadratic;

  Rectangle = Phaser.Rectangle;

  YELLOW = 0xffff00;

  WHITE = 0xffffff;

  onDown = function(sprite) {
    sprite.tint = YELLOW;
  };

  onUp = function(sprite) {
    sprite.tint = WHITE;
    switch (sprite.text) {
      case "Start":
        this.tween.start();
        break;
      case "Stop":
        this.tween.stop();
        break;
      case "Pause":
        this.tween.pause();
        break;
      case "Resume":
        this.tween.resume();
    }
  };

  tweenGui = function(tween) {
    var gui;
    gui = new dat.GUI;
    gui.add(tween, "frameBased");
    gui.add(tween, "pendingDelete").listen();
    gui.add(tween, "loop");
    gui.add(tween, "pause");
    gui.add(tween, "repeatAll");
    gui.add(tween, "repeatCounter").listen();
    gui.add(tween, "resume");
    gui.add(tween, "reverse");
    gui.add(tween, "start");
    gui.add(tween, "stop");
    gui.add(tween, "timeScale", 0.25, 2, 0.25);
    return gui;
  };

  new Phaser.Game({
    antialias: false,
    width: 960,
    height: 1080,
    renderer: Phaser.CANVAS,
    scaleMode: Phaser.ScaleManager.NO_SCALE,
    state: {
      init: function() {
        var debug;
        this.game.plugins.add(Phaser.Plugin.DebugTween);
        debug = this.game.debug;
        debug.font = "16px monospace";
        debug.lineHeight = 20;
      },
      preload: function() {
        this.load.baseURL = "http://examples.phaser.io/assets/";
        this.load.crossOrigin = "anonymous";
        this.load.image("bunny", "sprites/bunny.png");
      },
      create: function() {
        var TURN, buttons, centerX, centerY, style;
        centerX = this.world.centerX;
        centerY = this.world.centerY;
        TURN = 2 * Math.PI;
        this.sprite = this.add.sprite(centerX, -centerY, "bunny");
        this.sprite.anchor.set(0.5);
        this.tween = this.add.tween(this.sprite).to({
          y: 1.5 * centerY
        }, 1500, Bounce.Out).to({
          rotation: 1 * TURN,
          x: 2 * centerX
        }, 1000, Back.InOut).to({
          rotation: 0,
          x: centerX
        }, 1000, Back.InOut, false, 500).to({
          alpha: 0,
          y: 2 * centerY
        }, 500, Quadratic.In);
        this.tween.timeScale = 0.5;
        this.time.events.add(250, (function() {
          this.gui = tweenGui(this.tween);
        }), this);
        buttons = this.add.group();
        buttons.inputEnableChildren = true;
        buttons.onChildInputDown.add(onDown, this);
        buttons.onChildInputUp.add(onUp, this);
        buttons.setAll("input.useHandCursor", true);
        style = {
          fill: "white",
          font: "32px cursive"
        };
        this.add.text(0, 0, "Start", style, buttons);
        this.add.text(0, 0, "Stop", style, buttons);
        this.add.text(0, 0, "Pause", style, buttons);
        this.add.text(0, 0, "Resume", style, buttons);
        buttons.x = 32;
        buttons.align(-1, 1, 120, 90);
        buttons.alignIn(this.game.camera.view, Phaser.TOP_CENTER);
        this.columns = [new Rectangle(0, 320, 320, 320).inflate(-20, 0), new Rectangle(320, 320, 320, 320).inflate(-20, 0), new Rectangle(640, 320, 320, 320).inflate(-20, 0)];
      },
      render: function() {
        var current, debug;
        debug = this.game.debug;
        current = this.tween.timeline[this.tween.current];
        debug.tween(this.tween, 20, 120);
        debug.tweenInfo(this.tween, this.columns[0].x, this.columns[0].y);
        debug.tweenDataInfo(current, this.columns[1].x, this.columns[1].y);
        debug.tweenDataValues(current, this.columns[2].x, this.columns[2].y);
        this.debugText("game.debug.tween(tween, x, y)", 20, 80);
        this.debugText("game.debug.tweenInfo(tween, x, y)", this.columns[0].x, this.columns[0].y - 100);
        this.debugText("game.debug.tweenDataInfo(tweenData, x, y)", this.columns[0].x, this.columns[0].y - 75);
        this.debugText("game.debug.tweenDataValues(tweenData, x, y)", this.columns[0].x, this.columns[0].y - 50);
      },
      shutdown: function() {
        this.gui.destroy();
      },
      debugText: function(text, x, y) {
        var debug;
        debug = this.game.debug;
        debug.text(text, x, y, "#999", debug.font);
      }
    }
  });

}).call(this);
